fixtures:
  repositories:
    concat:
      repo: "https://github.com/puppetlabs/puppetlabs-concat.git"
    stdlib:
      repo: "https://github.com/puppetlabs/puppetlabs-stdlib.git"
    facts: 'https://github.com/puppetlabs/puppetlabs-facts.git'
    puppet_agent:
			repo: 'https://github.com/puppetlabs/puppetlabs-puppet_agent.git'
			ref: v4.12.1
    provision: 'https://github.com/puppetlabs/provision.git'
  symlinks:
    haproxy: "#{source_dir}"
