fixtures:
  repositories:
    concat: 'git://github.com/puppetlabs/puppetlabs-concat.git'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib.git'
      ref: '3.0.0'
  symlinks:
    haproxy: "#{source_dir}"
